import { Cultivar, BatchGenealogy } from '../types/cultivar';

export const mockCultivars: Cultivar[] = [
  {
    id: 'cult-1',
    name: 'Blue Dream',
    type: 'seed',
    genetics: 'Blueberry x Haze',
    description: 'Balanced hybrid with sweet berry aroma',
    thcRange: { min: 17, max: 24 },
    cbdRange: { min: 0, max: 2 },
    floweringTime: 63,
    expectedYield: 0.45,
    createdAt: '2024-01-15T08:00:00Z',
    isActive: true,
  },
  {
    id: 'cult-2',
    name: 'OG Kush',
    type: 'clone',
    genetics: 'Chemdawg x Hindu Kush',
    description: 'Classic strain with earthy, pine notes',
    thcRange: { min: 20, max: 26 },
    cbdRange: { min: 0, max: 1 },
    floweringTime: 56,
    expectedYield: 0.40,
    createdAt: '2024-01-20T08:00:00Z',
    isActive: true,
  },
  {
    id: 'cult-3',
    name: 'Sour Diesel',
    type: 'seed',
    genetics: 'Chemdawg x Super Skunk',
    description: 'Energizing sativa with diesel aroma',
    thcRange: { min: 18, max: 22 },
    cbdRange: { min: 0, max: 1 },
    floweringTime: 70,
    expectedYield: 0.50,
    createdAt: '2024-02-01T08:00:00Z',
    isActive: true,
  },
  {
    id: 'cult-4',
    name: 'Girl Scout Cookies',
    type: 'clone',
    genetics: 'Durban Poison x OG Kush',
    description: 'Sweet and earthy hybrid',
    thcRange: { min: 25, max: 28 },
    cbdRange: { min: 0, max: 1 },
    floweringTime: 60,
    expectedYield: 0.42,
    createdAt: '2024-02-10T08:00:00Z',
    isActive: true,
  },
];

export const mockGenealogyRecords: BatchGenealogy[] = [
  {
    batchId: 'batch-1',
    source: 'seed',
    seedVendor: 'Premium Seeds Co.',
    seedLotNumber: 'PS-BD-2025-001',
    generationNumber: 1,
    notes: 'First generation from certified seed stock',
  },
  {
    batchId: 'batch-2',
    source: 'clone',
    parentBatchId: 'batch-archived-01',
    motherPlantId: 'plant-mother-05',
    generationNumber: 3,
    notes: 'Clone from proven mother plant',
  },
  {
    batchId: 'batch-3',
    source: 'seed',
    seedVendor: 'Elite Genetics',
    seedLotNumber: 'EG-SD-2025-003',
    generationNumber: 1,
  },
];
