import { Plant, DryingRoom } from '../types/harvest';

export const mockPlants: Plant[] = [
  {
    id: 'plant-001',
    tagId: 'TAG-2025-001',
    batchId: 'batch-1',
    location: 'Pod A1 - Row 1',
    status: 'flowering',
    plantedDate: '2025-01-15',
    strainName: 'Blue Dream',
  },
  {
    id: 'plant-002',
    tagId: 'TAG-2025-002',
    batchId: 'batch-1',
    location: 'Pod A1 - Row 1',
    status: 'flowering',
    plantedDate: '2025-01-15',
    strainName: 'Blue Dream',
  },
  {
    id: 'plant-003',
    tagId: 'TAG-2025-003',
    batchId: 'batch-1',
    location: 'Pod A1 - Row 2',
    status: 'flowering',
    plantedDate: '2025-01-15',
    strainName: 'Blue Dream',
  },
  {
    id: 'plant-004',
    tagId: 'TAG-2025-004',
    batchId: 'batch-1',
    location: 'Pod A1 - Row 2',
    status: 'flowering',
    plantedDate: '2025-01-15',
    strainName: 'Blue Dream',
  },
  {
    id: 'plant-005',
    tagId: 'TAG-2025-005',
    batchId: 'batch-1',
    location: 'Pod A2 - Row 1',
    status: 'flowering',
    plantedDate: '2025-01-15',
    strainName: 'Blue Dream',
  },
  {
    id: 'plant-006',
    tagId: 'TAG-2025-006',
    batchId: 'batch-1',
    location: 'Pod A2 - Row 1',
    status: 'flowering',
    plantedDate: '2025-01-15',
    strainName: 'Blue Dream',
  },
  {
    id: 'plant-007',
    tagId: 'TAG-2025-007',
    batchId: 'batch-1',
    location: 'Pod A2 - Row 2',
    status: 'flowering',
    plantedDate: '2025-01-15',
    strainName: 'Blue Dream',
  },
  {
    id: 'plant-008',
    tagId: 'TAG-2025-008',
    batchId: 'batch-1',
    location: 'Pod A2 - Row 2',
    status: 'flowering',
    plantedDate: '2025-01-15',
    strainName: 'Blue Dream',
  },
];

export const mockDryingRooms: DryingRoom[] = [
  {
    id: 'dry-room-1',
    name: 'Drying Room A',
    location: 'Building 1 - Level 2',
    capacity: 500,
    currentLoad: 250,
    temperature: 18.5,
    humidity: 55,
  },
  {
    id: 'dry-room-2',
    name: 'Drying Room B',
    location: 'Building 1 - Level 2',
    capacity: 500,
    currentLoad: 150,
    temperature: 18.2,
    humidity: 53,
  },
  {
    id: 'dry-room-3',
    name: 'Drying Room C',
    location: 'Building 2 - Level 1',
    capacity: 750,
    currentLoad: 100,
    temperature: 18.8,
    humidity: 54,
  },
];
