import { Cultivar, BatchGenealogy } from '../types/cultivar';

export const mockCultivars: Cultivar[] = [
  {
    id: 'cult-1',
    name: 'Blue Dream',
    type: 'seed',
    strainType: 'sativa-dominant',
    genetics: 'Blueberry x Haze',
    description: 'Balanced hybrid with sweet berry aroma and uplifting effects',
    thcRange: { min: 17, max: 24 },
    cbdRange: { min: 0.1, max: 2 },
    terpeneProfile: ['Myrcene', 'Pinene', 'Caryophyllene'],
    floweringTime: 63,
    expectedYield: 450,
    growthCharacteristics: 'Tall plants with moderate stretch, good lateral branching',
    createdAt: '2024-01-15T08:00:00Z',
    isActive: true,
  },
  {
    id: 'cult-2',
    name: 'OG Kush',
    type: 'clone',
    strainType: 'hybrid',
    genetics: 'Chemdawg x Hindu Kush',
    description: 'Classic strain with earthy, pine, and lemon notes',
    thcRange: { min: 20, max: 26 },
    cbdRange: { min: 0, max: 1 },
    terpeneProfile: ['Limonene', 'Myrcene', 'Caryophyllene'],
    floweringTime: 56,
    expectedYield: 400,
    growthCharacteristics: 'Medium height, dense bud structure, prone to powdery mildew',
    createdAt: '2024-01-20T08:00:00Z',
    isActive: true,
  },
  {
    id: 'cult-3',
    name: 'Sour Diesel',
    type: 'seed',
    strainType: 'sativa',
    genetics: 'Chemdawg x Super Skunk',
    description: 'Energizing sativa with pungent diesel aroma',
    thcRange: { min: 18, max: 22 },
    cbdRange: { min: 0, max: 1 },
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Myrcene'],
    floweringTime: 70,
    expectedYield: 500,
    growthCharacteristics: 'Tall plants with significant stretch, requires support',
    createdAt: '2024-02-01T08:00:00Z',
    isActive: true,
  },
  {
    id: 'cult-4',
    name: 'Girl Scout Cookies',
    type: 'clone',
    strainType: 'indica-dominant',
    genetics: 'Durban Poison x OG Kush',
    description: 'Sweet and earthy hybrid with dessert-like flavors',
    thcRange: { min: 25, max: 28 },
    cbdRange: { min: 0, max: 1 },
    terpeneProfile: ['Caryophyllene', 'Limonene', 'Humulene'],
    floweringTime: 60,
    expectedYield: 420,
    growthCharacteristics: 'Short, bushy plants with tight node spacing and purple hues',
    createdAt: '2024-02-10T08:00:00Z',
    isActive: true,
  },
  {
    id: 'cult-5',
    name: 'Gorilla Glue #4',
    type: 'clone',
    strainType: 'hybrid',
    genetics: "Chem's Sister x Sour Dubb x Chocolate Diesel",
    description: 'Heavy-hitting hybrid known for extreme resin production',
    thcRange: { min: 25, max: 30 },
    cbdRange: { min: 0, max: 0.5 },
    terpeneProfile: ['Caryophyllene', 'Myrcene', 'Limonene'],
    floweringTime: 56,
    expectedYield: 600,
    growthCharacteristics: 'Vigorous growth, extremely sticky buds, requires defoliation',
    createdAt: '2024-02-15T08:00:00Z',
    isActive: true,
  },
  {
    id: 'cult-6',
    name: 'Wedding Cake',
    type: 'clone',
    strainType: 'indica-dominant',
    genetics: 'Triangle Kush x Animal Mints',
    description: 'Sweet, tangy strain with vanilla and earthy notes',
    thcRange: { min: 23, max: 27 },
    cbdRange: { min: 0, max: 1 },
    terpeneProfile: ['Limonene', 'Caryophyllene', 'Humulene'],
    floweringTime: 63,
    expectedYield: 480,
    growthCharacteristics: 'Compact plants with dense, frosty buds',
    createdAt: '2024-03-01T08:00:00Z',
    isActive: true,
  },
];

export const mockGenealogyRecords: BatchGenealogy[] = [
  {
    batchId: 'batch-1',
    source: 'seed',
    seedVendor: 'Premium Seeds Co.',
    seedLotNumber: 'PS-BD-2025-001',
    generationNumber: 1,
    notes: 'First generation from certified seed stock',
  },
  {
    batchId: 'batch-2',
    source: 'clone',
    parentBatchId: 'batch-archived-01',
    motherPlantId: 'plant-mother-05',
    generationNumber: 3,
    notes: 'Clone from proven mother plant',
  },
  {
    batchId: 'batch-3',
    source: 'seed',
    seedVendor: 'Elite Genetics',
    seedLotNumber: 'EG-SD-2025-003',
    generationNumber: 1,
  },
];
