import { 
  WaterTestRecord, 
  ChemicalApplicationRecord, 
  WorkerHygieneLog,
  SanitationLog,
  PestControlLog,
  SupplierApproval,
  NonConformanceReport,
  TraceabilityTest,
  InternalAudit,
  CustomerComplaint,
  TrainingRecord
} from '../types/compliance';

export const mockWaterTests: WaterTestRecord[] = [
  {
    id: 'water-001',
    testDate: '2025-03-15',
    waterSource: 'Well #1',
    sourceType: 'well',
    location: 'North Field',
    sampleId: 'WS-2025-0315-001',
    testedBy: 'Sarah Johnson',
    laboratory: 'AgriTest Labs',
    parameters: {
      ecoli: { value: 0, unit: 'CFU/100ml', limit: 0, passed: true },
      totalColiform: { value: 2, unit: 'CFU/100ml', limit: 100, passed: true },
      pH: { value: 7.2, passed: true },
      turbidity: { value: 0.5, unit: 'NTU', limit: 5, passed: true },
    },
    overallResult: 'pass',
    nextTestDue: '2025-04-15',
    verifiedBy: 'Mike Davis',
    verifiedAt: '2025-03-16T10:00:00Z',
  },
  {
    id: 'water-002',
    testDate: '2025-02-28',
    waterSource: 'Municipal Supply',
    sourceType: 'municipal',
    location: 'Pack House',
    sampleId: 'WS-2025-0228-002',
    testedBy: 'Maria Garcia',
    parameters: {
      ecoli: { value: 0, unit: 'CFU/100ml', limit: 0, passed: true },
      chlorine: { value: 1.5, unit: 'ppm', passed: true },
      pH: { value: 7.8, passed: true },
    },
    overallResult: 'pass',
    nextTestDue: '2025-03-31',
    verifiedBy: 'Mike Davis',
    verifiedAt: '2025-03-01T09:00:00Z',
  },
];

export const mockChemicalApplications: ChemicalApplicationRecord[] = [
  {
    id: 'chem-001',
    applicationDate: '2025-03-10',
    batchId: 'batch-1',
    growingAreaId: 'area-1',
    productType: 'pesticide',
    productName: 'PyGanic 5.0 EC',
    epaRegistration: '1021-1771',
    activeIngredients: ['Pyrethrins'],
    applicationRate: '4.5 oz per 1000 sq ft',
    applicationMethod: 'spray',
    targetPest: 'Aphids',
    totalArea: 2000,
    totalAmount: 9,
    unit: 'oz',
    phi: 0, // can harvest same day
    rei: 12, // 12 hours
    applicatorName: 'John Martinez',
    applicatorLicense: 'CA-AG-45678',
    weatherConditions: 'Clear, light breeze',
    temperature: 68,
    windSpeed: 5,
    preHarvestCompliance: true,
    supervisorApproval: 'Mike Davis',
    approvedAt: '2025-03-10T07:00:00Z',
  },
  {
    id: 'chem-002',
    applicationDate: '2025-02-15',
    growingAreaId: 'area-2',
    productType: 'fertilizer',
    productName: 'Organic Fish Emulsion 5-1-1',
    activeIngredients: ['Fish hydrolysate', 'Kelp extract'],
    applicationRate: '2 tablespoons per gallon',
    applicationMethod: 'drip',
    totalArea: 1500,
    totalAmount: 5,
    unit: 'gallons',
    phi: 0,
    rei: 0,
    applicatorName: 'Sarah Johnson',
    weatherConditions: 'Overcast',
    temperature: 62,
    preHarvestCompliance: true,
    supervisorApproval: 'Mike Davis',
    approvedAt: '2025-02-15T08:30:00Z',
  },
];

export const mockHygieneLogs: WorkerHygieneLog[] = [
  {
    id: 'hygiene-001',
    date: '2025-03-20',
    shift: 'morning',
    location: 'Greenhouse 1',
    inspectorName: 'Maria Garcia',
    inspectionType: 'routine',
    checklistItems: {
      handwashingStationsStocked: true,
      toiletFacilitiesClean: true,
      workersWearingGloves: true,
      workersInCleanUniforms: true,
      noIllnessReported: true,
      noOpenWounds: true,
      personalItemsStored: true,
    },
    workersInspected: 12,
    violations: [],
    correctiveActions: [],
    followUpRequired: false,
    notes: 'All workers compliant with hygiene protocols',
  },
  {
    id: 'hygiene-002',
    date: '2025-03-19',
    shift: 'afternoon',
    location: 'Pack House',
    inspectorName: 'Sarah Johnson',
    inspectionType: 'spot_check',
    checklistItems: {
      handwashingStationsStocked: true,
      toiletFacilitiesClean: true,
      workersWearingGloves: false,
      workersInCleanUniforms: true,
      noIllnessReported: true,
      noOpenWounds: true,
      personalItemsStored: true,
    },
    workersInspected: 8,
    violations: ['Two workers not wearing gloves at sorting station'],
    correctiveActions: ['Immediate glove distribution', 'Retrained workers on glove policy'],
    followUpRequired: true,
    followUpDate: '2025-03-21',
    notes: 'Workers retrained on the spot',
  },
];

export const mockSanitationLogs: SanitationLog[] = [
  {
    id: 'sanit-001',
    date: '2025-03-20',
    facilityArea: 'Pack House - Sorting Line',
    equipmentType: 'Conveyor Belt & Sorting Table',
    cleaningType: 'post_operational',
    cleaningAgent: 'EcoLab Peroxide Multi Surface Cleaner',
    sanitizer: 'Quaternary Ammonium',
    sanitizerConcentration: 200,
    startTime: '17:00',
    endTime: '17:45',
    cleanedBy: 'James Wilson',
    verifiedBy: 'Sarah Johnson',
    verificationMethod: 'atp_swab',
    verificationResult: 'pass',
    nextScheduledCleaning: '2025-03-21',
  },
  {
    id: 'sanit-002',
    date: '2025-03-20',
    facilityArea: 'Washing Station A',
    equipmentType: 'Produce Washer',
    cleaningType: 'deep_clean',
    cleaningAgent: 'Diversey Oxonia Active',
    sanitizer: 'Peroxyacetic Acid',
    sanitizerConcentration: 80,
    startTime: '06:00',
    endTime: '07:30',
    cleanedBy: 'Carlos Rodriguez',
    verifiedBy: 'Mike Davis',
    verificationMethod: 'visual',
    verificationResult: 'pass',
    nextScheduledCleaning: '2025-04-20',
    notes: 'Monthly deep clean completed',
  },
];

export const mockPestControl: PestControlLog[] = [
  {
    id: 'pest-001',
    inspectionDate: '2025-03-18',
    inspectorName: 'Tom Anderson',
    company: 'SafeGuard Pest Management',
    licenseNumber: 'CA-PCO-9876',
    location: 'Pack House Perimeter',
    areaType: 'perimeter',
    pestActivity: {
      rodents: 'none',
      insects: 'low',
      birds: 'none',
    },
    trapsChecked: 24,
    newTrapsPlaced: 0,
    baitStationsServiced: 12,
    findings: 'Minor ant activity near loading dock, addressed with bait stations',
    correctiveActions: ['Additional bait stations placed', 'Sealed gaps in loading dock doors'],
    followUpRequired: true,
    nextInspectionDate: '2025-04-18',
  },
];

export const mockSupplierApprovals: SupplierApproval[] = [
  {
    id: 'sup-001',
    supplierName: "Johnny's Selected Seeds",
    supplierType: 'seed',
    contactInfo: {
      address: '955 Benton Avenue, Winslow, ME 04901',
      phone: '1-877-564-6697',
      email: 'info@johnnyseeds.com',
      contactPerson: 'Customer Service',
    },
    approvalStatus: 'approved',
    approvalDate: '2024-01-15',
    expiryDate: '2026-01-15',
    certifications: ['Organic Certified', 'Safe Seed Pledge'],
    auditScore: 95,
    lastAuditDate: '2024-01-10',
    approvedProducts: ['Roma Tomato Seeds', 'Butterhead Lettuce Seeds', 'Basil Seeds'],
    riskLevel: 'low',
    approvedBy: 'Mike Davis',
    notes: 'Excellent supplier with consistent quality',
  },
  {
    id: 'sup-002',
    supplierName: 'Nourse Farms',
    supplierType: 'transplant',
    contactInfo: {
      address: '41 River Road, South Deerfield, MA 01373',
      phone: '413-665-2658',
      email: 'info@noursefarms.com',
      contactPerson: 'Sales Department',
    },
    approvalStatus: 'approved',
    approvalDate: '2024-02-01',
    expiryDate: '2026-02-01',
    certifications: ['Certified Disease-Free', 'USDA Inspected'],
    auditScore: 92,
    lastAuditDate: '2024-01-25',
    approvedProducts: ['Strawberry Transplants', 'Raspberry Canes'],
    riskLevel: 'low',
    approvedBy: 'Mike Davis',
  },
];

export const mockNonConformances: NonConformanceReport[] = [
  {
    id: 'ncr-001',
    reportDate: '2025-03-15',
    reportedBy: 'Sarah Johnson',
    category: 'food_safety',
    severity: 'major',
    location: 'Pack House - Washing Station',
    batchId: 'batch-2',
    description: 'Chlorine concentration in wash water below minimum threshold (0.8 ppm vs 1.0 ppm minimum)',
    rootCause: 'Automatic chlorine dispenser malfunction',
    immediateAction: 'Production stopped, dispenser repaired, water retested',
    correctiveAction: 'Replaced dispenser pump, implemented manual backup monitoring',
    preventiveAction: 'Added daily dispenser functionality check to SOP',
    responsiblePerson: 'Carlos Rodriguez',
    targetCompletionDate: '2025-03-16',
    actualCompletionDate: '2025-03-16',
    status: 'closed',
    verifiedBy: 'Mike Davis',
    verifiedAt: '2025-03-17T10:00:00Z',
    effectiveness: 'effective',
    followUpRequired: false,
  },
];

export const mockTraceabilityTests: TraceabilityTest[] = [
  {
    id: 'trace-001',
    testDate: '2025-02-28',
    testType: 'mock_recall',
    lotNumber: 'LOT-2025-001',
    batchId: 'batch-1',
    productName: 'Roma Tomato',
    startTime: '09:00',
    endTime: '10:45',
    durationMinutes: 105,
    targetTime: 240, // 4 hours
    result: 'pass',
    testedBy: 'Sarah Johnson',
    recordsRetrieved: {
      supplierRecords: true,
      productionRecords: true,
      packagingRecords: true,
      shippingRecords: true,
      customerRecords: true,
    },
    traceabilityAccuracy: 100,
    gaps: [],
    correctiveActions: [],
    verifiedBy: 'Mike Davis',
    notes: 'All records retrieved within 1 hour 45 minutes - well within target',
  },
];

export const mockInternalAudits: InternalAudit[] = [
  {
    id: 'audit-001',
    auditDate: '2025-01-15',
    auditType: 'comprehensive',
    auditor: 'External Auditor - Jane Smith',
    scope: ['Food Safety Policy', 'GAP', 'GMP', 'Traceability', 'Recordkeeping'],
    checklistItems: [
      {
        item: 'Food Safety Policy',
        requirement: 'Current policy posted and communicated to all staff',
        compliant: true,
        evidence: 'Policy posted in break rooms, training records reviewed',
      },
      {
        item: 'Water Testing',
        requirement: 'Monthly water tests with passing results',
        compliant: true,
        evidence: 'All water test records reviewed - 100% pass rate',
      },
      {
        item: 'Traceability',
        requirement: 'Mock recall completed annually',
        compliant: true,
        evidence: 'Last mock recall completed 2024-12-15 with passing result',
      },
    ],
    overallScore: 96,
    criticalFindings: 0,
    majorFindings: 1,
    minorFindings: 3,
    observations: ['Excellent recordkeeping system', 'Strong food safety culture'],
    strengths: ['Digital tracking system', 'Well-trained staff', 'Proactive corrective actions'],
    correctiveActionsRequired: ['Update pest control SOP to include new facility area'],
    followUpDate: '2025-07-15',
    status: 'completed',
    reportGeneratedAt: '2025-01-20T10:00:00Z',
  },
];

export const mockComplaints: CustomerComplaint[] = [];

export const mockTrainingRecords: TrainingRecord[] = [
  {
    id: 'train-001',
    trainingDate: '2025-01-10',
    trainingType: 'food_safety',
    topic: 'PrimusGFS Food Safety Fundamentals',
    duration: 4,
    trainerName: 'Mike Davis',
    trainerQualifications: 'Certified Food Safety Manager',
    attendees: [
      { employeeId: 'emp-001', employeeName: 'John Martinez', position: 'Harvest Lead', passed: true },
      { employeeId: 'emp-002', employeeName: 'Maria Garcia', position: 'QA Inspector', passed: true },
      { employeeId: 'emp-003', employeeName: 'Sarah Johnson', position: 'Pack House Manager', passed: true },
      { employeeId: 'emp-004', employeeName: 'Carlos Rodriguez', position: 'Sanitation Lead', passed: true },
    ],
    materials: ['PrimusGFS Manual', 'Company SOP Handbook'],
    assessmentConducted: true,
    passingScore: 80,
    certificateIssued: true,
    expiryDate: '2026-01-10',
    nextTrainingDue: '2026-01-10',
  },
  {
    id: 'train-002',
    trainingDate: '2025-02-15',
    trainingType: 'hygiene',
    topic: 'Worker Hygiene and Personal Practices',
    duration: 2,
    trainerName: 'Sarah Johnson',
    attendees: [
      { employeeId: 'emp-005', employeeName: 'James Wilson', position: 'Harvest Worker', passed: true },
      { employeeId: 'emp-006', employeeName: 'Lisa Chen', position: 'Packing Worker', passed: true },
    ],
    materials: ['Hygiene SOP', 'Visual Guides'],
    assessmentConducted: true,
    passingScore: 80,
    certificateIssued: true,
    nextTrainingDue: '2026-02-15',
  },
];
