import { ProduceVariety, BatchGenealogy } from '../types/cultivar';

export const mockProduceVarieties: ProduceVariety[] = [
  {
    id: 'var-1',
    name: 'Roma VF',
    commonName: 'Roma Tomato',
    scientificName: 'Solanum lycopersicum',
    category: 'vegetable',
    type: 'seed',
    description: 'Determinate paste tomato, disease-resistant, excellent for sauces',
    growingDays: 75,
    expectedYield: 2.5, // lbs per plant
    flavorProfile: 'Rich, low acid, meaty',
    storageLife: 7,
    optimalTemp: { min: 65, max: 85 },
    createdAt: '2024-01-15T08:00:00Z',
    isActive: true,
  },
  {
    id: 'var-2',
    name: 'Buttercrunch',
    commonName: 'Butterhead Lettuce',
    scientificName: 'Lactuca sativa',
    category: 'leafy_green',
    type: 'seed',
    description: 'Tender butter lettuce with soft leaves, heat tolerant',
    growingDays: 55,
    expectedYield: 0.5, // lbs per sq ft
    flavorProfile: 'Mild, buttery, sweet',
    storageLife: 5,
    optimalTemp: { min: 60, max: 70 },
    createdAt: '2024-01-20T08:00:00Z',
    isActive: true,
  },
  {
    id: 'var-3',
    name: 'Chandler',
    commonName: 'Chandler Strawberry',
    scientificName: 'Fragaria × ananassa',
    category: 'fruit',
    type: 'transplant',
    description: 'Large, firm berries with excellent flavor, June-bearing',
    growingDays: 120,
    expectedYield: 1.5, // lbs per plant
    flavorProfile: 'Sweet, aromatic, classic strawberry',
    storageLife: 3,
    optimalTemp: { min: 60, max: 80 },
    createdAt: '2024-02-01T08:00:00Z',
    isActive: true,
  },
  {
    id: 'var-4',
    name: 'California Wonder',
    commonName: 'Bell Pepper Mix',
    scientificName: 'Capsicum annuum',
    category: 'vegetable',
    type: 'transplant',
    description: 'Classic bell pepper, turns red when mature, thick walls',
    growingDays: 75,
    expectedYield: 3.0, // lbs per plant
    flavorProfile: 'Sweet when ripe, mild',
    storageLife: 10,
    optimalTemp: { min: 70, max: 85 },
    createdAt: '2024-02-10T08:00:00Z',
    isActive: true,
  },
  {
    id: 'var-5',
    name: 'Nantes',
    commonName: 'Nantes Carrot',
    scientificName: 'Daucus carota',
    category: 'root_vegetable',
    type: 'seed',
    description: 'Cylindrical, sweet carrots with crisp texture',
    growingDays: 70,
    expectedYield: 0.8, // lbs per sq ft
    flavorProfile: 'Sweet, crisp, classic carrot',
    storageLife: 30,
    optimalTemp: { min: 60, max: 70 },
    createdAt: '2024-03-01T08:00:00Z',
    isActive: true,
  },
  {
    id: 'var-6',
    name: 'Genovese',
    commonName: 'Basil',
    scientificName: 'Ocimum basilicum',
    category: 'herb',
    type: 'seed',
    description: 'Classic Italian basil, large aromatic leaves',
    growingDays: 60,
    expectedYield: 0.3, // lbs per sq ft
    flavorProfile: 'Sweet, aromatic, peppery',
    storageLife: 3,
    optimalTemp: { min: 70, max: 85 },
    createdAt: '2024-03-15T08:00:00Z',
    isActive: true,
  },
];

export const mockGenealogyRecords: BatchGenealogy[] = [
  {
    batchId: 'batch-1',
    source: 'seed',
    seedVendor: 'Johnny\'s Selected Seeds',
    seedLotNumber: 'JS-ROMA-2025-001',
    generationNumber: 1,
    notes: 'Certified organic seed stock',
  },
  {
    batchId: 'batch-2',
    source: 'seed',
    seedVendor: 'High Mowing Organic Seeds',
    seedLotNumber: 'HM-BUTTER-2025-008',
    generationNumber: 1,
    notes: 'Started in greenhouse, transplanted to high tunnel',
  },
  {
    batchId: 'batch-3',
    source: 'transplant',
    seedVendor: 'Nourse Farms',
    seedLotNumber: 'NF-CHAND-2025-012',
    generationNumber: 1,
    notes: 'Bare root transplants, cold-stored before planting',
  },
  {
    batchId: 'batch-4',
    source: 'transplant',
    seedVendor: 'Local Greenhouse Supply',
    seedLotNumber: 'LGS-PEPPER-2024-445',
    generationNumber: 1,
    notes: 'Started from seed, transplanted at 6-week stage',
  },
];
