import { ProducePlant, PostHarvestFacility, HarvestRecord } from '../types/harvest';

export const mockProducePlants: ProducePlant[] = [
  {
    id: 'plant-001',
    bedNumber: 'B-01',
    rowNumber: 'R-1',
    batchId: 'batch-1',
    location: 'Greenhouse 1 - North Section',
    status: 'growing',
    plantedDate: '2025-01-15',
    varietyName: 'Roma Tomato',
  },
  {
    id: 'plant-002',
    bedNumber: 'B-01',
    rowNumber: 'R-2',
    batchId: 'batch-1',
    location: 'Greenhouse 1 - North Section',
    status: 'growing',
    plantedDate: '2025-01-15',
    varietyName: 'Roma Tomato',
  },
  {
    id: 'plant-003',
    bedNumber: 'B-02',
    rowNumber: 'R-1',
    batchId: 'batch-1',
    location: 'Greenhouse 1 - South Section',
    status: 'ready_to_harvest',
    plantedDate: '2025-01-15',
    varietyName: 'Roma Tomato',
  },
  {
    id: 'plant-004',
    bedNumber: 'B-02',
    rowNumber: 'R-2',
    batchId: 'batch-1',
    location: 'Greenhouse 1 - South Section',
    status: 'ready_to_harvest',
    plantedDate: '2025-01-15',
    varietyName: 'Roma Tomato',
  },
  {
    id: 'plant-005',
    bedNumber: 'B-03',
    rowNumber: 'R-1',
    batchId: 'batch-2',
    location: 'High Tunnel A',
    status: 'growing',
    plantedDate: '2025-02-01',
    varietyName: 'Butterhead Lettuce',
  },
  {
    id: 'plant-006',
    bedNumber: 'B-03',
    rowNumber: 'R-2',
    batchId: 'batch-2',
    location: 'High Tunnel A',
    status: 'growing',
    plantedDate: '2025-02-01',
    varietyName: 'Butterhead Lettuce',
  },
  {
    id: 'plant-007',
    bedNumber: 'B-04',
    rowNumber: 'R-1',
    batchId: 'batch-3',
    location: 'Outdoor Field 1',
    status: 'seedling',
    plantedDate: '2025-03-10',
    varietyName: 'Chandler Strawberry',
  },
  {
    id: 'plant-008',
    bedNumber: 'B-04',
    rowNumber: 'R-2',
    batchId: 'batch-3',
    location: 'Outdoor Field 1',
    status: 'seedling',
    plantedDate: '2025-03-10',
    varietyName: 'Chandler Strawberry',
  },
];

export const mockPostHarvestFacilities: PostHarvestFacility[] = [
  {
    id: 'facility-1',
    name: 'Washing Station A',
    type: 'washing_station',
    location: 'Pack House - Bay 1',
    capacity: 1000, // lbs
    currentLoad: 450,
    temperature: 55,
    humidity: 85,
  },
  {
    id: 'facility-2',
    name: 'Washing Station B',
    type: 'washing_station',
    location: 'Pack House - Bay 2',
    capacity: 1000,
    currentLoad: 200,
    temperature: 54,
    humidity: 87,
  },
  {
    id: 'facility-3',
    name: 'Cold Storage Room 1',
    type: 'cold_storage',
    location: 'Cooler Building',
    capacity: 5000,
    currentLoad: 2800,
    temperature: 38,
    humidity: 90,
  },
  {
    id: 'facility-4',
    name: 'Cold Storage Room 2',
    type: 'cold_storage',
    location: 'Cooler Building',
    capacity: 5000,
    currentLoad: 1200,
    temperature: 36,
    humidity: 92,
  },
  {
    id: 'facility-5',
    name: 'Sorting Area',
    type: 'sorting_area',
    location: 'Pack House - Central',
    capacity: 800,
    currentLoad: 350,
    temperature: 65,
    humidity: 60,
  },
  {
    id: 'facility-6',
    name: 'Packaging Line 1',
    type: 'packaging_area',
    location: 'Pack House - East Wing',
    capacity: 500,
    currentLoad: 200,
    temperature: 65,
    humidity: 55,
  },
];

export const mockHarvestRecords: HarvestRecord[] = [
  {
    id: 'harvest-001',
    batchId: 'batch-1',
    harvestZone: 'Greenhouse 1 - Section A',
    bedRows: ['B-01-R1', 'B-01-R2', 'B-01-R3'],
    totalWeight: 285,
    grade: 'Grade A',
    harvestedBy: 'John Martinez',
    harvestDate: '2025-03-20',
    destinationLocation: 'Washing Station A',
    temperature: 72,
    qualityNotes: 'Excellent fruit quality, picked at optimal ripeness',
  },
  {
    id: 'harvest-002',
    batchId: 'batch-1',
    harvestZone: 'Greenhouse 1 - Section B',
    bedRows: ['B-02-R1', 'B-02-R2'],
    totalWeight: 195,
    grade: 'Grade A',
    harvestedBy: 'Maria Garcia',
    harvestDate: '2025-03-21',
    destinationLocation: 'Washing Station A',
    temperature: 68,
    qualityNotes: 'Good color and firmness',
  },
  {
    id: 'harvest-003',
    batchId: 'batch-2',
    harvestZone: 'High Tunnel A',
    bedRows: ['B-03-R1', 'B-03-R2', 'B-03-R3', 'B-03-R4'],
    totalWeight: 145,
    grade: 'Grade A',
    harvestedBy: 'Sarah Johnson',
    harvestDate: '2025-03-25',
    destinationLocation: 'Cold Storage Room 1',
    temperature: 58,
    qualityNotes: 'Harvested early morning, excellent crispness',
  },
];
