/**
 * Batch and Cultivar Seed Data
 * Sample batches for cannabis and produce domains
 */

import type { DomainType, CannabisStage, ProduceStage, BatchStatus } from '@/types/batch'

// Sample Cultivars
export const SEED_CULTIVARS = [
  // Cannabis Cultivars
  {
    id: 'cultivar-cannabis-001',
    organization_id: 'org-001', // Green Valley Cultivation
    name: 'Blue Dream',
    common_name: 'Blue Dream',
    description: 'Popular hybrid strain known for balanced effects',
    growing_days: 65,
    expected_yield: 450,
    is_active: true,
    created_at: new Date('2025-01-15').toISOString(),
  },
  {
    id: 'cultivar-cannabis-002',
    organization_id: 'org-001',
    name: 'OG Kush',
    common_name: 'OG Kush',
    description: 'Classic indica-dominant strain',
    growing_days: 55,
    expected_yield: 400,
    is_active: true,
    created_at: new Date('2025-01-15').toISOString(),
  },
  {
    id: 'cultivar-cannabis-003',
    organization_id: 'org-001',
    name: 'Sour Diesel',
    common_name: 'Sour Diesel',
    description: 'Energizing sativa-dominant strain',
    growing_days: 70,
    expected_yield: 500,
    is_active: true,
    created_at: new Date('2025-01-15').toISOString(),
  },
  
  // Produce Cultivars
  {
    id: 'cultivar-produce-001',
    organization_id: 'org-001',
    name: 'Roma Tomato',
    common_name: 'Roma',
    description: 'Classic plum tomato variety',
    growing_days: 75,
    expected_yield: 8000,
    category: 'vegetable',
    flavor_profile: 'Rich, sweet with low acidity',
    storage_life_days: 14,
    is_active: true,
    created_at: new Date('2025-01-15').toISOString(),
  },
  {
    id: 'cultivar-produce-002',
    organization_id: 'org-001',
    name: 'Butterhead Lettuce',
    common_name: 'Buttercrunch',
    description: 'Tender, sweet lettuce variety',
    growing_days: 50,
    expected_yield: 12000,
    category: 'leafy_green',
    flavor_profile: 'Mild, buttery, slightly sweet',
    storage_life_days: 7,
    is_active: true,
    created_at: new Date('2025-01-15').toISOString(),
  },
  {
    id: 'cultivar-produce-003',
    organization_id: 'org-001',
    name: 'Basil Sweet Genovese',
    common_name: 'Sweet Basil',
    description: 'Classic Italian basil',
    growing_days: 60,
    expected_yield: 5000,
    category: 'herb',
    flavor_profile: 'Sweet, slightly spicy, aromatic',
    storage_life_days: 10,
    is_active: true,
    created_at: new Date('2025-01-15').toISOString(),
  },
]

// Sample Batches
export const SEED_BATCHES = [
  // Cannabis Batches
  {
    id: 'batch-cannabis-001',
    organization_id: 'org-001',
    site_id: 'site-001', // Main Facility
    batch_number: 'CBD-2025-001',
    cultivar_id: 'cultivar-cannabis-001', // Blue Dream
    domain_type: 'cannabis' as DomainType,
    stage: 'flowering' as CannabisStage,
    plant_count: 48,
    start_date: new Date('2025-09-15').toISOString(),
    expected_harvest_date: new Date('2025-11-20').toISOString(),
    status: 'active' as BatchStatus,
    lighting_schedule: '12/12',
    source_type: 'clone',
    notes: 'Week 5 of flowering, looking healthy',
    created_by: 'user-001',
    created_at: new Date('2025-09-15').toISOString(),
    updated_at: new Date('2025-11-10').toISOString(),
  },
  {
    id: 'batch-cannabis-002',
    organization_id: 'org-001',
    site_id: 'site-001',
    batch_number: 'COK-2025-002',
    cultivar_id: 'cultivar-cannabis-002', // OG Kush
    domain_type: 'cannabis' as DomainType,
    stage: 'vegetative' as CannabisStage,
    plant_count: 96,
    start_date: new Date('2025-10-01').toISOString(),
    expected_harvest_date: new Date('2025-12-15').toISOString(),
    status: 'active' as BatchStatus,
    lighting_schedule: '18/6',
    source_type: 'clone',
    notes: 'Strong vegetative growth',
    created_by: 'user-001',
    created_at: new Date('2025-10-01').toISOString(),
    updated_at: new Date('2025-11-10').toISOString(),
  },
  {
    id: 'batch-cannabis-003',
    organization_id: 'org-001',
    site_id: 'site-001',
    batch_number: 'CSD-2025-003',
    cultivar_id: 'cultivar-cannabis-003', // Sour Diesel
    domain_type: 'cannabis' as DomainType,
    stage: 'drying' as CannabisStage,
    plant_count: 60,
    start_date: new Date('2025-07-15').toISOString(),
    expected_harvest_date: new Date('2025-10-01').toISOString(),
    actual_harvest_date: new Date('2025-10-28').toISOString(),
    status: 'active' as BatchStatus,
    drying_date: new Date('2025-10-28').toISOString(),
    yield_weight_g: 27500,
    yield_units: 55,
    notes: 'Drying day 10, humidity at 55%',
    created_by: 'user-001',
    created_at: new Date('2025-07-15').toISOString(),
    updated_at: new Date('2025-11-07').toISOString(),
  },
  {
    id: 'batch-cannabis-004',
    organization_id: 'org-001',
    site_id: 'site-001',
    batch_number: 'CBD-2025-004',
    cultivar_id: 'cultivar-cannabis-001', // Blue Dream
    domain_type: 'cannabis' as DomainType,
    stage: 'clone' as CannabisStage,
    plant_count: 200,
    start_date: new Date('2025-11-05').toISOString(),
    expected_harvest_date: new Date('2026-01-20').toISOString(),
    status: 'active' as BatchStatus,
    lighting_schedule: '24/0',
    source_type: 'clone',
    notes: 'Fresh clone batch, rooting well',
    created_by: 'user-002',
    created_at: new Date('2025-11-05').toISOString(),
    updated_at: new Date('2025-11-10').toISOString(),
  },
  {
    id: 'batch-cannabis-005',
    organization_id: 'org-001',
    site_id: 'site-001',
    batch_number: 'COK-2025-005',
    cultivar_id: 'cultivar-cannabis-002', // OG Kush
    domain_type: 'cannabis' as DomainType,
    stage: 'vegetative' as CannabisStage,
    plant_count: 72,
    start_date: new Date('2025-09-20').toISOString(),
    status: 'active' as BatchStatus,
    lighting_schedule: '18/6',
    source_type: 'clone',
    quarantine_reason: 'Suspected powdery mildew - under observation',
    quarantined_at: new Date('2025-11-08').toISOString(),
    quarantined_by: 'user-003',
    notes: 'Quarantined for inspection and treatment',
    created_by: 'user-001',
    created_at: new Date('2025-09-20').toISOString(),
    updated_at: new Date('2025-11-08').toISOString(),
  },

  // Produce Batches
  {
    id: 'batch-produce-001',
    organization_id: 'org-001',
    site_id: 'site-001',
    batch_number: 'PRT-2025-001',
    cultivar_id: 'cultivar-produce-001', // Roma Tomato
    domain_type: 'produce' as DomainType,
    stage: 'growing' as ProduceStage,
    plant_count: 500,
    start_date: new Date('2025-09-01').toISOString(),
    expected_harvest_date: new Date('2025-11-15').toISOString(),
    status: 'active' as BatchStatus,
    grade: 'A',
    ripeness: 'turning',
    source_type: 'seed',
    notes: 'Fruit development progressing well',
    created_by: 'user-002',
    created_at: new Date('2025-09-01').toISOString(),
    updated_at: new Date('2025-11-10').toISOString(),
  },
  {
    id: 'batch-produce-002',
    organization_id: 'org-001',
    site_id: 'site-001',
    batch_number: 'PLT-2025-002',
    cultivar_id: 'cultivar-produce-002', // Butterhead Lettuce
    domain_type: 'produce' as DomainType,
    stage: 'harvest_ready' as ProduceStage,
    plant_count: 1200,
    start_date: new Date('2025-09-25').toISOString(),
    expected_harvest_date: new Date('2025-11-14').toISOString(),
    status: 'active' as BatchStatus,
    grade: 'A',
    ripeness: 'ripe',
    firmness: 'Excellent',
    color: 'Bright green',
    defect_rate: 2.5,
    certifications: {
      organic: true,
      gap: true,
    },
    source_type: 'seed',
    notes: 'Ready for harvest, excellent quality',
    created_by: 'user-002',
    created_at: new Date('2025-09-25').toISOString(),
    updated_at: new Date('2025-11-12').toISOString(),
  },
  {
    id: 'batch-produce-003',
    organization_id: 'org-001',
    site_id: 'site-001',
    batch_number: 'PBS-2025-003',
    cultivar_id: 'cultivar-produce-003', // Basil
    domain_type: 'produce' as DomainType,
    stage: 'growing' as ProduceStage,
    plant_count: 800,
    start_date: new Date('2025-10-01').toISOString(),
    expected_harvest_date: new Date('2025-12-01').toISOString(),
    status: 'active' as BatchStatus,
    grade: 'A',
    source_type: 'seed',
    notes: 'Vigorous growth, aromatic',
    created_by: 'user-002',
    created_at: new Date('2025-10-01').toISOString(),
    updated_at: new Date('2025-11-10').toISOString(),
  },
  {
    id: 'batch-produce-004',
    organization_id: 'org-001',
    site_id: 'site-001',
    batch_number: 'PRT-2025-004',
    cultivar_id: 'cultivar-produce-001', // Roma Tomato
    domain_type: 'produce' as DomainType,
    stage: 'packing' as ProduceStage,
    plant_count: 400,
    start_date: new Date('2025-08-01').toISOString(),
    expected_harvest_date: new Date('2025-10-15').toISOString(),
    actual_harvest_date: new Date('2025-10-18').toISOString(),
    status: 'active' as BatchStatus,
    grade: 'A',
    ripeness: 'ripe',
    yield_weight_g: 3200000, // 3200 kg
    yield_units: 400,
    brix_level: 4.5,
    firmness: 'Firm',
    color: 'Deep red',
    defect_rate: 3.2,
    certifications: {
      organic: true,
      gap: true,
      primus_gfs: true,
    },
    notes: 'Harvested and in packing stage',
    created_by: 'user-002',
    created_at: new Date('2025-08-01').toISOString(),
    updated_at: new Date('2025-10-20').toISOString(),
  },
]
